### ISSUE TITLE
Security Issue

### ISSUE THREAD

**Issue by ousamabenyounes** [olifil/rezopouce-dev#15]
Your parameters.yml file has been compromised and your login/pwd are now visible on this link:
https://github.com/olifil/rezopouce-dev/blob/master/app/config/parameters-ovh.yml

to remove it from your history:
https://help.github.com/articles/removing-sensitive-data-from-a-repository/

Change your login/pwd on all your projects...

I recommand you also to use a gitignore file on the root of your Symfony project:
https://github.com/github/gitignore/blob/master/Symfony.gitignore
This will automatically ignore your parameters.yml file, your vendors ...

Hope this will help you :)

**Comment by olifil** [comment]
Files that have been removed from the history :

1. parameters.yml
2. parameters-ovh.yml
3. parameters-vps.yml

**Comment by ousamabenyounes** [comment]
We can still view your source code here:
https://github.com/olifil/rezopouce-dev/commit/4d622d060964cdb1a37448597e229654467714e9

apply this to remove it from your project or remove the project and create a new one
https://help.github.com/articles/removing-sensitive-data-from-a-repository/
